apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: citz-imb-sso-react-helper-developers-guide
  title: CITZ IMB SSO React Helper Developer's Guide
  description: This npm package offers an integration solution for React
    applications requiring authentication through the B.C. government's Single
    Sign-On SSO (CSS) service. It abstracts the complexity of handling SSO
    protocols manually. By using this package, developers can quickly implement
    authentication and authorization in their React applications to meet B.C.
    government security standards.
  annotations:
    github.com/project-slug: bcgov/citz-imb-sso-react
    backstage.io/techdocs-ref: dir:.
    bcgovpubcode.gov.bc.ca/ministry: CITZ
    bcgovpubcode.gov.bc.ca/product_name: citz-imb-sso-react
    bcgovpubcode.gov.bc.ca/product_owner: Laura Benson
    developer.gov.bc.ca/source_template: default/docs-template-pr
spec:
  type: documentation
  lifecycle: experimental
  owner: group:default/citz-imb-common-code
