site_name: 'CITZ IMB SSO React (NPM Package)'
site_description: "An npm package that offers an integration solution for connecting React applications requiring authentication to the B.C. government's Single Sign-On service."
docs_dir: 'techdocs/docs'
repo_url: 'https://github.com/bcgov/citz-imb-sso-react'
edit_uri: edit/main/techdocs/docs
nav:
  - Introduction: index.md
  - Getting Started:
      - Installing the Package: getting-started/installing-the-package.md
      - Quick Start Guide: getting-started/quick-start-guide.md
      - SSO Integration Settings: getting-started/sso-integration-settings.md
      - Proxy Pass:
          - Setting Up a Proxy Pass: getting-started/proxy-pass/setting-up-a-proxy-pass.md
          - Not Using a Proxy Pass: getting-started/proxy-pass/not-using-a-proxy-pass.md
  - Using the Package:
      - Calling a Protected Route: using-the-package/calling-a-protected-route.md
      - Getting User Information: using-the-package/getting-user-information.md
      - Custom Session Expiry Function: using-the-package/custom-session-expiry-function.md
      - APIs & Components:
          - SSOProvider: using-the-package/apis-&-components/provider.md
          - useSSO: using-the-package/apis-&-components/usesso.md
          - useSSO Actions:
              - login: using-the-package/apis-&-components/usesso-actions/login.md
              - logout: using-the-package/apis-&-components/usesso-actions/logout.md
              - isAuthenticated: using-the-package/apis-&-components/usesso-actions/is-authenticated.md
              - user: using-the-package/apis-&-components/usesso-actions/user.md
              - hasRoles: using-the-package/apis-&-components/usesso-actions/has-roles.md
              - fetchProtectedRoute: using-the-package/apis-&-components/usesso-actions/fetch-protected-route.md
              - getAuthorizationHeaderValue: using-the-package/apis-&-components/usesso-actions/get-auth-header-value.md
      - Module Exports: using-the-package/module-exports.md
      - TypeScript Types: using-the-package/typescript-types.md
      - Troubleshooting: using-the-package/troubleshooting.md
  - Major Releases:
      - 1.0.0: major-releases/major-release-1.md
  - Purpose and Benefits of this Package: purpose-and-benefits.md
  - Authentication Flow: authentication-flow.md

plugins:
  - techdocs-core
  - git-revision-date-localized
markdown_extensions:
  - md_in_html
